# shellcheck shell=bash
# Shared helpers for Tars's install/ops scripts. Source this; don't execute it.
# Keeps setup.sh / service.sh / doctor.sh / tunnel.sh small and consistent.

# Repo root = parent of this scripts/ directory (handles spaces in the path).
TARS_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$TARS_LIB_DIR/.." && pwd)"
export REPO_ROOT

# --- Pretty logging ---------------------------------------------------------
if [[ -t 1 ]]; then
  _C_RESET=$'\033[0m'; _C_BLUE=$'\033[34m'; _C_GREEN=$'\033[32m'
  _C_YELLOW=$'\033[33m'; _C_RED=$'\033[31m'; _C_BOLD=$'\033[1m'
else
  _C_RESET=''; _C_BLUE=''; _C_GREEN=''; _C_YELLOW=''; _C_RED=''; _C_BOLD=''
fi

step() { printf '\n%s==>%s %s%s%s\n' "$_C_BLUE" "$_C_RESET" "$_C_BOLD" "$*" "$_C_RESET"; }
info() { printf '    %s\n' "$*"; }
ok()   { printf '    %s✓%s %s\n' "$_C_GREEN" "$_C_RESET" "$*"; }
warn() { printf '    %s!%s %s\n' "$_C_YELLOW" "$_C_RESET" "$*" >&2; }
err()  { printf '    %s✗%s %s\n' "$_C_RED" "$_C_RESET" "$*" >&2; }
die()  { err "$*"; exit 1; }

# --- OS detection -----------------------------------------------------------
is_macos() { [[ "$(uname -s)" == "Darwin" ]]; }

# Bail early on non-macOS with a pointer to the manual path. Linux support is
# intentionally out of scope for these scripts (Colima/launchd/brew assumed).
require_macos() {
  if ! is_macos; then
    err "These scripts target macOS (Homebrew + Colima + launchd)."
    err "On Linux: install Docker + Node 20+ + Ollama natively, run 'pnpm install &&"
    err "pnpm build && pnpm db:up', and supervise 'pnpm start' with systemd instead."
    exit 1
  fi
}

# --- Command / Homebrew helpers --------------------------------------------
have() { command -v "$1" >/dev/null 2>&1; }

require_brew() {
  if ! have brew; then
    die "Homebrew is required. Install it from https://brew.sh then re-run 'make setup'."
  fi
}

# brew_install <formula> [check-cmd]  — install only if the check command is absent.
brew_install() {
  local formula="$1" check="${2:-$1}"
  if have "$check"; then
    ok "$check already installed"
  else
    info "Installing $formula via Homebrew..."
    brew install "$formula"
    ok "$formula installed"
  fi
}

# --- Postgres / Docker volume awareness ------------------------------------
# True if a Postgres data volume from a previous install already exists. Used to
# avoid rotating the DB password out from under existing data (the golden rule:
# never destroy the brain). Requires the docker daemon to be reachable.
data_volume_exists() {
  docker volume ls -q 2>/dev/null | grep -qiE 'tars.*pgdata'
}

# generate_password — URL-safe (hex only, so no DATABASE_URL escaping needed).
generate_password() {
  if have openssl; then openssl rand -hex 24; else
    head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# ensure_env — create .env and deploy/docker/.env if missing, with a real password.
#
# Golden rule: never destroy the brain. Postgres only applies POSTGRES_PASSWORD on an
# EMPTY data dir, so rotating it against an existing volume would lock out the data.
# Therefore: fresh install (no .env, no volume) → generate a strong password; an existing
# volume → preserve the legacy default it was initialized with. Requires docker reachable.
ensure_env() {
  local env_file="$REPO_ROOT/.env"
  local docker_env="$REPO_ROOT/deploy/docker/.env"
  local pw

  if [[ -f "$env_file" ]]; then
    pw="$(grep -E '^POSTGRES_PASSWORD=' "$env_file" | head -1 | cut -d= -f2-)"
    [[ -n "$pw" ]] || die "$env_file exists but has no POSTGRES_PASSWORD line."
    ok ".env present — keeping its POSTGRES_PASSWORD (not rotating)"
  else
    if data_volume_exists; then
      pw="tars_dev_password_change_me"
      warn "Existing Postgres volume found — preserving its password to protect existing data."
      warn "To rotate: stop the server, 'docker volume rm \$(docker volume ls -q | grep pgdata)'"
      warn "(DESTROYS the brain), delete .env, then re-run 'make setup'."
    else
      pw="$(generate_password)"
      ok "Fresh install — generated a strong POSTGRES_PASSWORD"
    fi
    write_app_env "$env_file" "$pw"
    ok "Wrote $env_file"
  fi

  if [[ ! -f "$docker_env" ]]; then
    write_docker_env "$docker_env" "$pw"
    ok "Wrote $docker_env"
  fi
}

write_app_env() {
  local path="$1" pw="$2"
  cat >"$path" <<EOF
# Tars — generated by 'make setup'. Edit as needed; NEVER commit this file.

# --- Postgres ---------------------------------------------------------------
POSTGRES_USER=tars
POSTGRES_PASSWORD=$pw
POSTGRES_DB=tars
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
DATABASE_URL=postgresql://tars:$pw@localhost:5432/tars

# --- Server -----------------------------------------------------------------
PORT=8787
HOST=127.0.0.1
PUBLIC_PORT=8788
# PUBLIC_BASE_URL is set by 'make tunnel' (written to ~/.tars/public.env and sourced
# by the launchd wrapper). Leave unset for loopback-only (Claude Code on this Mac).

# --- Embeddings -------------------------------------------------------------
EMBEDDING_PROVIDER=ollama
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_EMBEDDING_MODEL=nomic-embed-text
EOF
}

write_docker_env() {
  local path="$1" pw="$2"
  cat >"$path" <<EOF
# Postgres credentials for deploy/docker/docker-compose.yml. Generated by 'make setup'.
# Must match POSTGRES_PASSWORD / DATABASE_URL in the repo-root .env. NEVER commit.
POSTGRES_USER=tars
POSTGRES_PASSWORD=$pw
POSTGRES_DB=tars
POSTGRES_PORT=5432
EOF
}

# Wait (bounded) until the tars-postgres container reports healthy.
wait_for_postgres() {
  local tries="${1:-60}"
  for _ in $(seq 1 "$tries"); do
    local status
    status="$(docker inspect -f '{{.State.Health.Status}}' tars-postgres 2>/dev/null || true)"
    if [[ "$status" == "healthy" ]]; then return 0; fi
    sleep 1
  done
  # Fall back to a raw TCP probe in case the container has no healthcheck handle.
  nc -z 127.0.0.1 5432 >/dev/null 2>&1
}

# --- launchd ----------------------------------------------------------------
LAUNCHD_LABEL="com.tars.server"
LAUNCHD_PLIST="$HOME/Library/LaunchAgents/${LAUNCHD_LABEL}.plist"
launchd_target() { echo "gui/$(id -u)/${LAUNCHD_LABEL}"; }
launchd_loaded() { launchctl print "$(launchd_target)" >/dev/null 2>&1; }

# --- Server health ----------------------------------------------------------
# The loopback MCP endpoint answers 400 to a bare GET (no MCP session) when up.
server_http_code() {
  curl -s -o /dev/null -m 3 -w '%{http_code}' "http://127.0.0.1:${1:-8787}/mcp" 2>/dev/null || echo 000
}
server_up() { [[ "$(server_http_code "${1:-8787}")" != "000" ]]; }
