#!/usr/bin/env bash
# make tunnel — expose Tars's public OAuth listener over Tailscale Funnel so chat
# Claude (web/desktop/mobile) can reach it. Idempotent.
#
# Prereq (manual, one-time): install the STANDALONE Tailscale (not the App Store build —
# it can't run Funnel), 'tailscale up', and enable Funnel for this node in the admin
# console. See deploy/tunnel/README.md.
#
# Usage:  make tunnel                 (auto-detects this node's MagicDNS hostname)
#         TARS_TS_HOST=foo.ts.net make tunnel   (override hostname explicitly)
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

require_macos

# Locate the tailscale CLI (the standalone app ships it inside the bundle).
TS=""
for cand in tailscale /Applications/Tailscale.app/Contents/MacOS/Tailscale; do
  if command -v "$cand" >/dev/null 2>&1 || [[ -x "$cand" ]]; then TS="$cand"; break; fi
done
[[ -n "$TS" ]] || die "tailscale CLI not found. Install the STANDALONE Tailscale build (https://tailscale.com/download/macos), run 'tailscale up', then re-run 'make tunnel'."

step "Resolving Tailscale hostname"
HOST="${TARS_TS_HOST:-}"
if [[ -z "$HOST" ]]; then
  # Parse the node's MagicDNS name from 'tailscale status --json' using node (no jq dep).
  HOST="$("$TS" status --json 2>/dev/null | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const j=JSON.parse(s);const n=(j.Self&&j.Self.DNSName)||"";process.stdout.write(n.replace(/\.$/,""))}catch{}})')"
fi
[[ -n "$HOST" ]] || die "Could not determine the Tailscale hostname. Run 'tailscale up' first, or pass TARS_TS_HOST=<machine>.<tailnet>.ts.net."
ok "Hostname: $HOST"

PUBLIC_PORT="${PUBLIC_PORT:-8788}"
BASE_URL="https://$HOST"

step "Writing public OAuth config (~/.tars/public.env)"
mkdir -p "$HOME/.tars"
cat >"$HOME/.tars/public.env" <<EOF
# Generated by 'make tunnel'. Sourced by ops/launchd/tars-server-run.sh so the public
# (OAuth) listener comes up. PUBLIC_BASE_URL is the OAuth issuer AND the RFC 8707 resource
# identifier — it must exactly equal the hostname clients reach.
PUBLIC_BASE_URL=$BASE_URL
PUBLIC_PORT=$PUBLIC_PORT
EOF
ok "Wrote ~/.tars/public.env"

step "Restarting Tars so it picks up the public listener"
if launchd_loaded; then
  launchctl kickstart -k "$(launchd_target)"
  ok "Service restarted"
else
  warn "launchd service not loaded — run 'make install-service'. Continuing to set up Funnel."
fi

step "Starting Tailscale Funnel (443 → 127.0.0.1:$PUBLIC_PORT)"
"$TS" funnel --bg --https=443 "http://127.0.0.1:$PUBLIC_PORT"
ok "Funnel started"

step "Verifying OAuth discovery endpoints"
verify_ok=1
for _ in $(seq 1 15); do
  if curl -fs -m 5 "$BASE_URL/.well-known/oauth-authorization-server" >/dev/null 2>&1 \
     && curl -fs -m 5 "$BASE_URL/.well-known/oauth-protected-resource" >/dev/null 2>&1; then
    verify_ok=0; break
  fi
  sleep 2
done
if [[ "$verify_ok" -eq 0 ]]; then
  ok "Discovery endpoints reachable at $BASE_URL"
else
  warn "Discovery endpoints not reachable yet — give it a minute, then check:"
  warn "  curl $BASE_URL/.well-known/oauth-authorization-server"
  warn "  '$TS' funnel status"
fi

step "Done — connect chat Claude"
info "claude.ai → Settings → Connectors → Add custom connector:"
info "  URL:    $BASE_URL/mcp"
info "  Secret: (leave blank)"
info "Then paste docs/tars-system-prompt.md into the project / custom instructions."
